In [2]:
def ferriswheel(age,money):
    if(age >=15) and (money >=30):
        return "we are getting a ride"
    elif(age>=15) and (money<30):
        return "ask your parnets for a ticket"
    elif(age<15) and (money>=5):
        return "nice try kid!!!"
    else:
        return "You need to grow old "
print(ferriswheel(16,30))
print(ferriswheel(16,25))
print(ferriswheel(13,25))


we are getting a ride
ask your parnets for a ticket
nice try kid!!!


In [3]:
d = {
   'foo': 10,
   'bar': 20,
   'baz': 30
}

print(sum(d.values()))

60


In [4]:
#Question 1
def  TalkWithXia(string):
    flag=0
    for ele in string:
        if(ele.islower()):
            flag=1
    if(flag==0):
        if(string[-1]=='?'):
            print("Calm down, I know what I'm doing!")
        elif(string[-1]=='!'):
            print("Whoa, chill out!")
        else:
            print("Fine. Be that way!")
    else:
        if(string[-1]=='?'):
            print("Sure")
        elif(string[-1]=='!'):
            print("Whatever")
        else:
            print("Fine. Be that way!")
print("********* TalkWithXia *********")
string=input("Input: ")
TalkWithXia(string)

********* TalkWithXia *********


In [ ]:
#Question 2
def AlphabetWar(string):
    l_count=0
    r_count=0
    for letter in string:
        if letter in l_dic.keys():
            l_count+=l_dic[letter]
        elif letter in r_dic.keys():
            r_count+=r_dic[letter]
    if(l_count>r_count):
        print("Left side wins! by ",l_count-r_count)
    elif(r_count>l_count):
        print("Right side wins! by ",r_count-l_count)
    else:
        print("Let's fight again!")
        
l_dic={'w':4,
       'p':3,
       'b':2,
       's':1}
r_dic={'m':4,
       'q':3,
       'd':2,
       'z':1}
print("*********** PYTHON GEEK ***********")
string=input("Enter the String of war: ")
AlphabetWar(string)

In [ ]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))
print(x3)
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)
print("x3 itemsiz:",x3.itemsize,"")
print("nbytes:",x3.nbytes,"bytes")

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 itemsiz: 4 
nbytes: 240 bytes
